In [1]:
import numpy as np


In [12]:
em_scores = [28.89,	70.68,	13.33,	2.24,
32.96,	73.15,	19.05,	5.60,
28.08,	38.57,	29.51,	15.00,
53.13,	76.23,	47.62,	37.25,]

In [13]:
meteor_scores = [28.72,	64.81, 	16.45,	5.73,
32.25,	66.47,	20.08,	9.16,
31.23,	42.08,	30.95,	19.14,
47.88,	66.09,	41.74,	38.19,]

In [14]:
bert_scores = [50.52,	79.20,	46.35,	24.55,
53.99,	81.37,	47.36,	29.79,
47.71,	59.41,	51.19,	33.80,
68.36,	83.64,	67.46,	55.06]

In [15]:
np.corrcoef(meteor_scores, em_scores)

array([[1.        , 0.99464829],
       [0.99464829, 1.        ]])

In [16]:
np.corrcoef(meteor_scores, bert_scores)

array([[1.        , 0.97272004],
       [0.97272004, 1.        ]])

In [17]:
np.corrcoef(em_scores, bert_scores)

array([[1.        , 0.97944337],
       [0.97944337, 1.        ]])